export const mockDashboardLegacyFile = [
  {
    id: "file-101",
    name: "線性代數期末考解答",
    year: "2024",
    grade: "大一",
    semester: 2,
    teacher: "林志誠",
    subject: "線性代數",
    code: "MATH1001",
    type: "考古題",
    description: "112 下學期線性代數期末考試題與解答，含解析。",
    uploadedAt: "2025-07-25 16:20",
  },
  {
    id: "file-102",
    name: "C++ 期中專題",
    year: "2023",
    grade: "大二",
    semester: 1,
    teacher: "張凱翔",
    subject: "物件導向程式設計",
    code: "CS2002",
    type: "專題報告",
    description: "小組製作貪食蛇遊戲，內含原始碼與簡報。",
    uploadedAt: "2025-06-30 11:03",
  },
  {
    id: "file-103",
    name: "微積分一筆記",
    year: "2022",
    grade: "大一",
    semester: 1,
    teacher: "陳美娟",
    subject: "微積分（一）",
    code: "MATH1003",
    type: "課堂筆記",
    description: "課堂整理筆記，含各章例題與解法。",
    uploadedAt: "2025-04-18 09:42",
  },
];
